import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-gray-900 text-gray-100 min-h-screen">
        <div className="flex min-h-screen">
          <aside className="w-56 bg-gray-800 p-6 flex flex-col gap-4">
            <div className="text-2xl font-bold text-primary mb-8">Invoxa</div>
            <nav className="flex flex-col gap-2">
              <Link href="/dashboard" className="hover:text-primary">Dashboard</Link>
              <Link href="/create" className="hover:text-primary">Create Invoice</Link>
              <Link href="/clients" className="hover:text-primary">Clients</Link>
              <Link href="/settings" className="hover:text-primary">Settings</Link>
            </nav>
          </aside>
          <main className="flex-1">
            <header className="bg-gray-800 px-8 py-4 flex items-center justify-between">
              <span className="font-semibold text-lg">Billing System</span>
              <span className="text-gray-400">v0.1</span>
            </header>
            <div>{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
